name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            sheet_01/assignment_01.tex
            sheet_02/assignment_02.tex
            sheet_03/assignment_03.tex
            sheet_04/assignment_04.tex
            sheet_05/assignment_05.tex
            sheet_06/assignment_06.tex
            sheet_07/assignment_07.tex
            sheet_08/assignment_08.tex
            sheet_09/assignment_09.tex
            sheet_10/assignment_10.tex
            sheet_11/assignment_11.tex
          latexmk_use_xelatex: true
          work_in_root_file_dir: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "**/build/assignment_*.pdf"
